### PR TITLE
Release 0.39.0

### LINKED ISSUE #63: Handle step failures by resubmitting the jobflow
Some steps commonly fail, but it should be safe to retry them immediately without requiring any intervention.  EER should observe when a failed step is safe to retry, and re-submit the failed step and the remainder of the jobflow.

### PR DESCRIPTION
**Pull request by istreeter**
EER now observes when a failed step is safe to retry, and re-submits the failed step and the remainder of the jobflow.

This splits the `run` method into a separate `run_persistent_mode` and `run_transient_mode`.  The new functionality is only possible with a persistent cluster; whereas a transient cluster terminates immediately before we have a chance to resubmit the jobflow.

I admit there is now code duplication between the two run modes.  It was not possible to merge the two run modes into a unified method, not without making substantial changes to other parts of the code.  I suggest this (inelegant!) implementation as a way to give us the desired behaviour without doing a substantial overhaul.

Pipelines using transient clusters can still take advantage of this new behaviour by switching to persistent mode but using `--persistent-jobflow-duration 1m` so the cluster always terminates upon completion.

I have tested both run modes by running the jobflow end to end in EMR.  My tests included simulating failed steps.

### CODE REVIEW

File: lib/snowplow-emr-etl-runner/emr_job.rb [hunk 1]
```diff
@@ -875,6 +1016,19 @@ def output_rdb_loader_logs(region, aws_access_key_id, aws_secret_key, log_level)
...
+              # This prevents overwriting the original log file in case this step gets retried.
+              s3.copy_object({
+                bucket: bucket,
+                copy_source: "/#{bucket}/#{key}",
+                key: "#{key}.#{attempt}",
+              })
+              s3.delete_object({
+                bucket: bucket,
+                key: key,
+              })
```
Comment (istreeter) [inline lib/snowplow-emr-etl-runner/emr_job.rb:1030]: This juggling of rdb log files was necessary when I thought the rdb load job could be retried.  However, now I have found out the rdb_load job must not be retried.

I don't know whether to go back and rip out this special handling of rdb log files, or whether to leave it now as potentially useful in future.
